// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PlayerData
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ServerData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ServerData GetRootAsServerData(ByteBuffer _bb) { return GetRootAsServerData(_bb, new ServerData()); }
  public static ServerData GetRootAsServerData(ByteBuffer _bb, ServerData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Message { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<PlayerData.ServerData> CreateServerData(FlatBufferBuilder builder,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(1);
    ServerData.AddMessage(builder, messageOffset);
    return ServerData.EndServerData(builder);
  }

  public static void StartServerData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(0, messageOffset.Value, 0); }
  public static Offset<PlayerData.ServerData> EndServerData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PlayerData.ServerData>(o);
  }
  public static void FinishServerDataBuffer(FlatBufferBuilder builder, Offset<PlayerData.ServerData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedServerDataBuffer(FlatBufferBuilder builder, Offset<PlayerData.ServerData> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
